import StyleDictionary from "style-dictionary";
import { fileHeader, formattedVariables } from "style-dictionary/utils";
import { transformGroups } from "style-dictionary/enums";

const THEME_HEADER = [
  "Generated by `npm run tokens:build` from DTCG JSON under tokens/.",
  "Do not edit this file by hand — change tokens/*.json sources then rebuild.",
  "",
  "Dual-token period (PostHog player-ux-world-v2):",
  "- Survey field-book roles: canvas, field-ink, field-ink-muted, flag(+ink/soft),",
  "  signal(+soft), trail(+soft), halt(+soft), rule — authored from direction QUALITY BAR",
  "  (figma_skipped; not a Figma Variables export).",
  "- Deprecated Broadcast HUD tokens remain (surface-*, ink*, action*, brand-blue*,",
  "  highlight*, status-*, map-canvas, border*, scrollbar-*, radius-hud-*, shadow-hud-*)",
  "  so flag-off chrome keeps working until Wave 6 flag kill.",
  "- Direction role `ink` / `ink-muted` map to CSS --color-field-ink* (HUD owns --color-ink).",
];

StyleDictionary.registerFormat({
  name: "css/tailwind-v4-theme",
  format: async ({ dictionary, options = {}, file }) => {
    const header = await fileHeader({
      file: {
        ...file,
        options: {
          ...file?.options,
          ...options,
          fileHeader: () => THEME_HEADER,
        },
      },
    });

    const variables = formattedVariables({
      format: "css",
      dictionary,
      outputReferences: options.outputReferences,
      outputReferenceFallbacks: options.outputReferenceFallbacks,
      formatting: {
        indentation: "  ",
        // Descriptions are surfaced via the block header + deprecated line comments.
        commentStyle: "none",
      },
      usesDtcg: true,
    });

    const commented = variables
      .split("\n")
      .filter((line) => line.trim().length > 0)
      .map((line) => {
        const match = line.match(/^\s*--([a-z0-9-]+):/);
        if (!match) return line;
        const token = dictionary.allTokens.find((t) => t.name === match[1]);
        if (!token) return line;
        const deprecated = token.$deprecated ?? token.deprecated;
        if (!deprecated) return line;
        const note =
          typeof deprecated === "string" ? deprecated : "deprecated";
        return `  /* deprecated: ${note} */\n${line}`;
      })
      .join("\n");

    return `${header}@theme {\n${commented}\n}\n`;
  },
});

/** @type {import('style-dictionary').Config} */
const config = {
  source: ["tokens/**/*.json"],
  platforms: {
    css: {
      transformGroup: transformGroups.css,
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/tailwind-v4-theme",
          options: {
            outputReferences: true,
          },
        },
      ],
    },
  },
};

export default config;
