/** @type {import('stylelint').Config} */
export default {
  extends: [
    "stylelint-config-standard",
    "@dreamsicle.io/stylelint-config-tailwindcss",
  ],
  ignoreFiles: [
    "**/node_modules/**",
    "**/dist/**",
    "coverage/**",
    ".worktrees/**",
    "target/**",
    "crates/*/pkg/**",
    // Generated by tokens:build until Wave 3 W3-B deletes the Style Dictionary pipeline
    "src/styles/tokens.css",
  ],
  rules: {
    // Motion-gated selectors intentionally reorder vs base chrome rules
    "no-descending-specificity": null,
    // House style: BEM --modifier / __element (standard default is kebab-only)
    "selector-class-pattern": [
      "^([a-z][a-z0-9_]*)((-|__|--)[a-z0-9_]+)*$",
      { resolveNestedSelectors: true },
    ],
  },
};
