export {
  MIN_DRAG_START_PX,
  SHEET_DISMISS_FRACTION,
  SHEET_VELOCITY_DISMISS_PX_MS,
  PANEL_SNAP_FRACTION,
  PANEL_MINIMIZE_VELOCITY_PX_MS,
  PANEL_EXPAND_VELOCITY_PX_MS,
  PANEL_PEEK_HEIGHT_PX,
  OVERLAY_DISMISS_FRACTION,
  OVERLAY_DISMISS_VELOCITY_PX_MS,
  WIZARD_SWIPE_AXIS_SLOP_PX,
  WIZARD_SWIPE_COMMIT_FRACTION,
  WIZARD_SWIPE_COMMIT_VELOCITY_PX_MS,
} from "./motionTokens";

import { PANEL_MINIMIZE_VELOCITY_PX_MS } from "./motionTokens";

/** Shared drag threshold for tool panel minimize (px). @deprecated Use PANEL_SNAP_FRACTION */
export const TOOL_PANEL_MINIMIZE_THRESHOLD_PX = 72;

/** Shared velocity threshold for tool panel minimize (px/ms). */
export const TOOL_PANEL_MINIMIZE_VELOCITY_PX_MS = PANEL_MINIMIZE_VELOCITY_PX_MS;
