/* Generated by scripts/sync-region-flags.mjs — do not edit by hand. */
export const BUNDLED_PRESET_FLAG_ASSETS = {
  "continent-europe": {
    "src": "/region-flags/continent-europe.png",
    "alt": "European Union",
    "source": "flagcdn:eu",
    "identity": "flagcdn:eu",
    "presentation": "flag"
  },
  "country-ireland": {
    "src": "/region-flags/country-ireland.png",
    "alt": "Ireland",
    "source": "flagcdn:ie",
    "identity": "flagcdn:ie",
    "presentation": "flag"
  },
  "country-uk": {
    "src": "/region-flags/country-uk.png",
    "alt": "United Kingdom",
    "source": "flagcdn:gb",
    "identity": "flagcdn:gb",
    "presentation": "flag"
  },
  "region-england": {
    "src": "/region-flags/region-england.png",
    "alt": "England",
    "source": "flagcdn:gb-eng",
    "identity": "flagcdn:gb-eng",
    "presentation": "flag"
  },
  "country-switzerland": {
    "src": "/region-flags/country-switzerland.png",
    "alt": "Switzerland",
    "source": "flagcdn:ch",
    "identity": "flagcdn:ch",
    "presentation": "flag"
  },
  "country-usa": {
    "src": "/region-flags/country-usa.png",
    "alt": "United States",
    "source": "flagcdn:us",
    "identity": "flagcdn:us",
    "presentation": "flag"
  },
  "country-canada": {
    "src": "/region-flags/country-canada.png",
    "alt": "Canada",
    "source": "flagcdn:ca",
    "identity": "flagcdn:ca",
    "presentation": "flag"
  },
  "country-japan": {
    "src": "/region-flags/country-japan.png",
    "alt": "Japan",
    "source": "flagcdn:jp",
    "identity": "flagcdn:jp",
    "presentation": "flag"
  },
  "continent-north-america": {
    "src": "/region-flags/continent-north-america.png",
    "alt": "Organization of American States",
    "source": "wikidata:Q123759:P41",
    "identity": "commons:flag of the organization of american states.svg",
    "presentation": "flag"
  },
  "continent-asia": {
    "src": "/region-flags/continent-asia.png",
    "alt": "ASEAN",
    "source": "wikidata:Q7768:commons",
    "identity": "commons:asean flag (1994).svg",
    "presentation": "flag"
  },
  "state-ny": {
    "src": "/region-flags/state-ny.png",
    "alt": "New York",
    "source": "wikidata:Q1384:P41",
    "identity": "commons:flag of new york.svg",
    "presentation": "flag"
  },
  "state-me": {
    "src": "/region-flags/state-me.png",
    "alt": "Maine",
    "source": "wikidata:Q724:P41",
    "identity": "commons:flag of maine.svg",
    "presentation": "flag"
  },
  "province-bc": {
    "src": "/region-flags/province-bc.png",
    "alt": "British Columbia",
    "source": "wikidata:Q1973:P41",
    "identity": "commons:flag of british columbia.svg",
    "presentation": "flag"
  },
  "canton-zurich": {
    "src": "/region-flags/canton-zurich.png",
    "alt": "Canton of Zürich",
    "source": "wikidata:Q11943:P41",
    "identity": "commons:che zürich flag.svg",
    "presentation": "flag"
  },
  "canton-lucerne": {
    "src": "/region-flags/canton-lucerne.png",
    "alt": "Canton of Lucerne",
    "source": "wikidata:Q12121:P41",
    "identity": "commons:che luzern flag.svg",
    "presentation": "flag"
  },
  "county-dublin": {
    "src": "/region-flags/county-dublin.png",
    "alt": "County Dublin",
    "source": "wikidata:Q173500:P41",
    "identity": "commons:colours of dublin.svg",
    "presentation": "flag"
  },
  "metro-london": {
    "src": "/region-flags/metro-london.png",
    "alt": "Greater London",
    "source": "wikidata:Q23306:P41",
    "identity": "commons:county flag of greater london.svg",
    "presentation": "flag"
  },
  "metro-nyc": {
    "src": "/region-flags/metro-nyc.png",
    "alt": "New York City",
    "source": "wikidata:Q60:P41",
    "identity": "commons:flag of new york city.svg",
    "presentation": "flag"
  },
  "metro-tokyo": {
    "src": "/region-flags/metro-tokyo.png",
    "alt": "Tokyo",
    "source": "wikidata:Q1490:P41",
    "identity": "commons:flag of tokyo metropolis.svg",
    "presentation": "flag"
  },
  "metro-osaka": {
    "src": "/region-flags/metro-osaka.png",
    "alt": "Osaka City",
    "source": "wikidata:Q35765:P41",
    "identity": "commons:flag of osaka, osaka.svg",
    "presentation": "flag"
  },
  "lucerne-metro": {
    "src": "/region-flags/lucerne-metro.png",
    "alt": "Lucerne",
    "source": "wikidata:Q4191:P41",
    "identity": "commons:che luzern flag.svg",
    "presentation": "flag"
  },
  "zurich-city": {
    "src": "/region-flags/zurich-city.png",
    "alt": "Zürich",
    "source": "wikidata:Q72:P41",
    "identity": "commons:che zürich flag.svg",
    "presentation": "flag"
  },
  "ward-13101": {
    "src": "/region-flags/ward-13101.png",
    "alt": "Chiyoda",
    "source": "wikidata:Q214051:P41",
    "identity": "commons:flag of chiyoda, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13102": {
    "src": "/region-flags/ward-13102.png",
    "alt": "Chūō",
    "source": "wikidata:Q212704:P41",
    "identity": "commons:flag of chuo, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13103": {
    "src": "/region-flags/ward-13103.png",
    "alt": "Minato",
    "source": "wikidata:Q190088:P41",
    "identity": "commons:flag of minato, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13104": {
    "src": "/region-flags/ward-13104.png",
    "alt": "Shinjuku",
    "source": "wikidata:Q179645:P41",
    "identity": "commons:flag of shinjuku, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13105": {
    "src": "/region-flags/ward-13105.png",
    "alt": "Bunkyō",
    "source": "wikidata:Q212713:P41",
    "identity": "commons:flag of bunkyo, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13106": {
    "src": "/region-flags/ward-13106.png",
    "alt": "Taitō",
    "source": "wikidata:Q232641:P41",
    "identity": "commons:flag of taito, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13107": {
    "src": "/region-flags/ward-13107.png",
    "alt": "Sumida",
    "source": "wikidata:Q235135:P41",
    "identity": "commons:flag of sumida, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13108": {
    "src": "/region-flags/ward-13108.png",
    "alt": "Kōtō",
    "source": "wikidata:Q215175:P41",
    "identity": "commons:flag of koto, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13109": {
    "src": "/region-flags/ward-13109.png",
    "alt": "Shinagawa",
    "source": "wikidata:Q233495:P41",
    "identity": "commons:flag of shinagawa, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13110": {
    "src": "/region-flags/ward-13110.png",
    "alt": "Meguro",
    "source": "wikidata:Q233903:P41",
    "identity": "commons:flag of meguro, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13111": {
    "src": "/region-flags/ward-13111.png",
    "alt": "Ōta",
    "source": "wikidata:Q217234:P41",
    "identity": "commons:flag of ota, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13112": {
    "src": "/region-flags/ward-13112.png",
    "alt": "Setagaya",
    "source": "wikidata:Q231645:P41",
    "identity": "commons:flag of setagaya, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13113": {
    "src": "/region-flags/ward-13113.png",
    "alt": "Shibuya",
    "source": "wikidata:Q193638:P41",
    "identity": "commons:flag of shibuya, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13114": {
    "src": "/region-flags/ward-13114.png",
    "alt": "Nakano",
    "source": "wikidata:Q234087:P41",
    "identity": "commons:flag of nakano, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13115": {
    "src": "/region-flags/ward-13115.png",
    "alt": "Suginami",
    "source": "wikidata:Q232631:P41",
    "identity": "commons:flag of suginami, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13116": {
    "src": "/region-flags/ward-13116.png",
    "alt": "Toshima",
    "source": "wikidata:Q236680:P41",
    "identity": "commons:flag of toshima, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13117": {
    "src": "/region-flags/ward-13117.png",
    "alt": "Kita",
    "source": "wikidata:Q235130:P41",
    "identity": "commons:flag of kita, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13118": {
    "src": "/region-flags/ward-13118.png",
    "alt": "Arakawa",
    "source": "wikidata:Q232624:P41",
    "identity": "commons:flag of arakawa, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13119": {
    "src": "/region-flags/ward-13119.png",
    "alt": "Itabashi",
    "source": "wikidata:Q232635:P41",
    "identity": "commons:flag of itabashi, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13120": {
    "src": "/region-flags/ward-13120.png",
    "alt": "Nerima",
    "source": "wikidata:Q232655:P41",
    "identity": "commons:flag of nerima, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13121": {
    "src": "/region-flags/ward-13121.png",
    "alt": "Adachi",
    "source": "wikidata:Q213464:P41",
    "identity": "commons:flag of adachi, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13122": {
    "src": "/region-flags/ward-13122.png",
    "alt": "Katsushika",
    "source": "wikidata:Q232628:P41",
    "identity": "commons:flag of katsushika, tokyo.svg",
    "presentation": "flag"
  },
  "ward-13123": {
    "src": "/region-flags/ward-13123.png",
    "alt": "Edogawa",
    "source": "wikidata:Q214056:P41",
    "identity": "commons:flag of edogawa, tokyo.svg",
    "presentation": "flag"
  },
  "barking-and-dagenham": {
    "src": "/region-flags/barking-and-dagenham.png",
    "alt": "Barking And Dagenham",
    "source": "wikidata:Q205358:P94",
    "identity": "commons:coat of arms of the london borough of barking and dagenham.svg",
    "presentation": "flag"
  },
  "barnet": {
    "src": "/region-flags/barnet.png",
    "alt": "Barnet",
    "source": "wikidata:Q151048:P94",
    "identity": "commons:coat of arms of the london borough of barnet.svg",
    "presentation": "cutout"
  },
  "bexley": {
    "src": "/region-flags/bexley.png",
    "alt": "Bexley",
    "source": "commons:Flag of the Borough of Bexley.gif",
    "identity": "commons:flag of the borough of bexley.gif",
    "presentation": "flag"
  },
  "brent": {
    "src": "/region-flags/brent.png",
    "alt": "Brent",
    "source": "wikidata:Q207201:P94",
    "identity": "commons:coat of arms of the london borough of brent.svg",
    "presentation": "cutout"
  },
  "bromley": {
    "src": "/region-flags/bromley.png",
    "alt": "Bromley",
    "source": "wikidata:Q208201:P94",
    "identity": "commons:coat of arms of the london borough of bromley.svg",
    "presentation": "cutout"
  },
  "camden": {
    "src": "/region-flags/camden.png",
    "alt": "Camden",
    "source": "wikidata:Q202088:P94",
    "identity": "commons:coat of arms of the london borough of camden.svg",
    "presentation": "cutout"
  },
  "city-of-london": {
    "src": "/region-flags/city-of-london.png",
    "alt": "City Of London",
    "source": "wikidata:Q23311:P41",
    "identity": "commons:flag of the city of london.svg",
    "presentation": "flag"
  },
  "city-of-westminster": {
    "src": "/region-flags/city-of-westminster.png",
    "alt": "City Of Westminster",
    "source": "commons:Flag of Westminster.png",
    "identity": "commons:flag of westminster.png",
    "presentation": "flag"
  },
  "croydon": {
    "src": "/region-flags/croydon.png",
    "alt": "Croydon",
    "source": "wikidata:Q26888:P94",
    "identity": "commons:coat of arms of the london borough of croydon.svg",
    "presentation": "cutout"
  },
  "ealing": {
    "src": "/region-flags/ealing.png",
    "alt": "Ealing",
    "source": "commons:Ealing Flag.png",
    "identity": "commons:ealing flag.png",
    "presentation": "flag"
  },
  "enfield": {
    "src": "/region-flags/enfield.png",
    "alt": "Enfield",
    "source": "wikidata:Q210531:P94",
    "identity": "commons:coat of arms of the london borough of enfield.svg",
    "presentation": "cutout"
  },
  "greenwich": {
    "src": "/region-flags/greenwich.png",
    "alt": "Greenwich",
    "source": "wikidata:Q693450:P94",
    "identity": "commons:coat of arms of the royal borough of greenwich.svg",
    "presentation": "cutout"
  },
  "hackney": {
    "src": "/region-flags/hackney.png",
    "alt": "Hackney",
    "source": "commons:Flag of the London Borough of Hackney.svg",
    "identity": "commons:flag of the london borough of hackney.svg",
    "presentation": "flag"
  },
  "hammersmith-and-fulham": {
    "src": "/region-flags/hammersmith-and-fulham.png",
    "alt": "Hammersmith And Fulham",
    "source": "wikidata:Q40478:P94",
    "identity": "commons:coat of arms of the london borough of hammersmith and fulham.svg",
    "presentation": "cutout"
  },
  "haringey": {
    "src": "/region-flags/haringey.png",
    "alt": "Haringey",
    "source": "commons:Flag of the London Borough of Haringey.svg",
    "identity": "commons:flag of the london borough of haringey.svg",
    "presentation": "flag"
  },
  "harrow": {
    "src": "/region-flags/harrow.png",
    "alt": "Harrow",
    "source": "wikidata:Q210476:P94",
    "identity": "commons:coat of arms of the london borough of harrow.svg",
    "presentation": "cutout"
  },
  "havering": {
    "src": "/region-flags/havering.png",
    "alt": "Havering",
    "source": "commons:Flag of the London Borough of Havering.svg",
    "identity": "commons:flag of the london borough of havering.svg",
    "presentation": "flag"
  },
  "hillingdon": {
    "src": "/region-flags/hillingdon.png",
    "alt": "Hillingdon",
    "source": "wikidata:Q205690:P94",
    "identity": "commons:coat of arms of the london borough of hillingdon.svg",
    "presentation": "cutout"
  },
  "hounslow": {
    "src": "/region-flags/hounslow.png",
    "alt": "Hounslow",
    "source": "wikidata:Q214162:P94",
    "identity": "commons:coat of arms of the london borough of hounslow.svg",
    "presentation": "cutout"
  },
  "islington": {
    "src": "/region-flags/islington.png",
    "alt": "Islington",
    "source": "commons:Flag of the London Borough of Islington.svg",
    "identity": "commons:flag of the london borough of islington.svg",
    "presentation": "flag"
  },
  "kensington-and-chelsea": {
    "src": "/region-flags/kensington-and-chelsea.png",
    "alt": "Kensington And Chelsea",
    "source": "wikidata:Q188801:P94",
    "identity": "commons:coat of arms of the royal borough of kensington and chelsea.svg",
    "presentation": "cutout"
  },
  "kingston-upon-thames": {
    "src": "/region-flags/kingston-upon-thames.png",
    "alt": "Kingston Upon Thames",
    "source": "commons:Flag of the London Borough of Kingston-upon-Thames.svg",
    "identity": "commons:flag of the london borough of kingston-upon-thames.svg",
    "presentation": "flag"
  },
  "lambeth": {
    "src": "/region-flags/lambeth.png",
    "alt": "Lambeth",
    "source": "wikidata:Q202059:P94",
    "identity": "commons:coat of arms of the london borough of lambeth.svg",
    "presentation": "cutout"
  },
  "lewisham": {
    "src": "/region-flags/lewisham.png",
    "alt": "Lewisham",
    "source": "wikidata:Q215030:P94",
    "identity": "commons:coat of arms of the london borough of lewisham.svg",
    "presentation": "cutout"
  },
  "merton": {
    "src": "/region-flags/merton.png",
    "alt": "Merton",
    "source": "wikidata:Q32504:P94",
    "identity": "commons:coat of arms of the london borough of merton.svg",
    "presentation": "cutout"
  },
  "newham": {
    "src": "/region-flags/newham.png",
    "alt": "Newham",
    "source": "wikidata:Q208139:P94",
    "identity": "commons:coat of arms of the london borough of newham.svg",
    "presentation": "cutout"
  },
  "richmond-upon-thames": {
    "src": "/region-flags/richmond-upon-thames.png",
    "alt": "Richmond Upon Thames",
    "source": "wikidata:Q32515:P94",
    "identity": "commons:coat of arms of the london borough of richmond upon thames.svg",
    "presentation": "cutout"
  },
  "southwark": {
    "src": "/region-flags/southwark.png",
    "alt": "Southwark",
    "source": "wikidata:Q730706:P94",
    "identity": "commons:coat of arms of the london borough of southwark.svg",
    "presentation": "cutout"
  },
  "sutton": {
    "src": "/region-flags/sutton.png",
    "alt": "Sutton",
    "source": "commons:Flag of the Borough of Sutton.jpg",
    "identity": "commons:flag of the borough of sutton.jpg",
    "presentation": "flag"
  },
  "tower-hamlets": {
    "src": "/region-flags/tower-hamlets.png",
    "alt": "Tower Hamlets",
    "source": "wikidata:Q208152:P94",
    "identity": "commons:coat of arms of the london borough of tower hamlets.svg",
    "presentation": "cutout"
  },
  "waltham-forest": {
    "src": "/region-flags/waltham-forest.png",
    "alt": "Waltham Forest",
    "source": "wikidata:Q40608:P94",
    "identity": "commons:coat of arms of the london borough of waltham forest.svg",
    "presentation": "cutout"
  },
  "wandsworth": {
    "src": "/region-flags/wandsworth.png",
    "alt": "Wandsworth",
    "source": "wikidata:Q210563:P94",
    "identity": "commons:coat of arms of the london borough of wandsworth.svg",
    "presentation": "cutout"
  },
  "bronx": {
    "src": "/region-flags/bronx.png",
    "alt": "Bronx",
    "source": "commons:Flag of Borough of the Bronx.svg",
    "identity": "commons:flag of borough of the bronx.svg",
    "presentation": "flag"
  },
  "brooklyn": {
    "src": "/region-flags/brooklyn.png",
    "alt": "Brooklyn",
    "source": "commons:Flag of Brooklyn, New York.svg",
    "identity": "commons:flag of brooklyn, new york.svg",
    "presentation": "flag"
  },
  "manhattan": {
    "src": "/region-flags/manhattan.png",
    "alt": "Manhattan",
    "source": "commons:Flag of the Borough of Manhattan.svg",
    "identity": "commons:flag of the borough of manhattan.svg",
    "presentation": "flag"
  },
  "queens": {
    "src": "/region-flags/queens.png",
    "alt": "Queens",
    "source": "commons:Flag of Queens, New York.svg",
    "identity": "commons:flag of queens, new york.svg",
    "presentation": "flag"
  },
  "ward-27127": {
    "src": "/region-flags/ward-27127.png",
    "alt": "Kita",
    "source": "osaka-ward-flower:01kita.jpg",
    "identity": "osaka-ward-flower:01kita.jpg",
    "presentation": "cutout"
  },
  "ward-27102": {
    "src": "/region-flags/ward-27102.png",
    "alt": "Miyakojima",
    "source": "osaka-ward-flower:02miyakojima.jpg",
    "identity": "osaka-ward-flower:02miyakojima.jpg",
    "presentation": "cutout"
  },
  "ward-27103": {
    "src": "/region-flags/ward-27103.png",
    "alt": "Fukushima",
    "source": "osaka-ward-flower:03fukushima.jpg",
    "identity": "osaka-ward-flower:03fukushima.jpg",
    "presentation": "cutout"
  },
  "ward-27104": {
    "src": "/region-flags/ward-27104.png",
    "alt": "Konohana",
    "source": "osaka-ward-flower:04konohana.jpg",
    "identity": "osaka-ward-flower:04konohana.jpg",
    "presentation": "cutout"
  },
  "ward-27128": {
    "src": "/region-flags/ward-27128.png",
    "alt": "Chūō",
    "source": "osaka-ward-flower:05chuo.jpg",
    "identity": "osaka-ward-flower:05chuo.jpg",
    "presentation": "cutout"
  },
  "ward-27106": {
    "src": "/region-flags/ward-27106.png",
    "alt": "Nishi",
    "source": "osaka-ward-flower:06nishi.jpg",
    "identity": "osaka-ward-flower:06nishi.jpg",
    "presentation": "cutout"
  },
  "ward-27107": {
    "src": "/region-flags/ward-27107.png",
    "alt": "Minato",
    "source": "osaka-ward-flower:07minato.jpg",
    "identity": "osaka-ward-flower:07minato.jpg",
    "presentation": "cutout"
  },
  "ward-27108": {
    "src": "/region-flags/ward-27108.png",
    "alt": "Taishō",
    "source": "osaka-ward-flower:08taisho.jpg",
    "identity": "osaka-ward-flower:08taisho.jpg",
    "presentation": "cutout"
  },
  "ward-27109": {
    "src": "/region-flags/ward-27109.png",
    "alt": "Tennōji",
    "source": "osaka-ward-flower:09tennoji.jpg",
    "identity": "osaka-ward-flower:09tennoji.jpg",
    "presentation": "cutout"
  },
  "ward-27111": {
    "src": "/region-flags/ward-27111.png",
    "alt": "Naniwa",
    "source": "osaka-ward-flower:10nianiwa.jpg",
    "identity": "osaka-ward-flower:10nianiwa.jpg",
    "presentation": "cutout"
  },
  "ward-27113": {
    "src": "/region-flags/ward-27113.png",
    "alt": "Nishi-Yodogawa",
    "source": "osaka-ward-flower:11nishiyodogawa.jpg",
    "identity": "osaka-ward-flower:11nishiyodogawa.jpg",
    "presentation": "cutout"
  },
  "ward-27123": {
    "src": "/region-flags/ward-27123.png",
    "alt": "Yodogawa",
    "source": "osaka-ward-flower:12yodogawa.jpg",
    "identity": "osaka-ward-flower:12yodogawa.jpg",
    "presentation": "cutout"
  },
  "ward-27114": {
    "src": "/region-flags/ward-27114.png",
    "alt": "Higashi-Yodogawa",
    "source": "osaka-ward-flower:13higashiyodogawa.jpg",
    "identity": "osaka-ward-flower:13higashiyodogawa.jpg",
    "presentation": "cutout"
  },
  "ward-27115": {
    "src": "/region-flags/ward-27115.png",
    "alt": "Higashinari",
    "source": "osaka-ward-flower:14higashinari.jpg",
    "identity": "osaka-ward-flower:14higashinari.jpg",
    "presentation": "cutout"
  },
  "ward-27116": {
    "src": "/region-flags/ward-27116.png",
    "alt": "Ikuno",
    "source": "osaka-ward-flower:15ikuno.jpg",
    "identity": "osaka-ward-flower:15ikuno.jpg",
    "presentation": "cutout"
  },
  "ward-27117": {
    "src": "/region-flags/ward-27117.png",
    "alt": "Asahi",
    "source": "osaka-ward-flower:16asahi.jpg",
    "identity": "osaka-ward-flower:16asahi.jpg",
    "presentation": "cutout"
  },
  "ward-27118": {
    "src": "/region-flags/ward-27118.png",
    "alt": "Jōtō",
    "source": "osaka-ward-flower:17joto.jpg",
    "identity": "osaka-ward-flower:17joto.jpg",
    "presentation": "cutout"
  },
  "ward-27124": {
    "src": "/region-flags/ward-27124.png",
    "alt": "Tsurumi",
    "source": "osaka-ward-flower:18tsurumi.jpg",
    "identity": "osaka-ward-flower:18tsurumi.jpg",
    "presentation": "cutout"
  },
  "ward-27119": {
    "src": "/region-flags/ward-27119.png",
    "alt": "Abeno",
    "source": "osaka-ward-flower:19abeno.jpg",
    "identity": "osaka-ward-flower:19abeno.jpg",
    "presentation": "cutout"
  },
  "ward-27125": {
    "src": "/region-flags/ward-27125.png",
    "alt": "Suminoe",
    "source": "osaka-ward-flower:20suminoe.jpg",
    "identity": "osaka-ward-flower:20suminoe.jpg",
    "presentation": "cutout"
  },
  "ward-27120": {
    "src": "/region-flags/ward-27120.png",
    "alt": "Sumiyoshi",
    "source": "osaka-ward-flower:21sumiyoshi.jpg",
    "identity": "osaka-ward-flower:21sumiyoshi.jpg",
    "presentation": "cutout"
  },
  "ward-27121": {
    "src": "/region-flags/ward-27121.png",
    "alt": "Higashi-Sumiyoshi",
    "source": "osaka-ward-flower:22higashisumiyoshi.jpg",
    "identity": "osaka-ward-flower:22higashisumiyoshi.jpg",
    "presentation": "cutout"
  },
  "ward-27126": {
    "src": "/region-flags/ward-27126.png",
    "alt": "Hirano",
    "source": "osaka-ward-flower:23hirano.jpg",
    "identity": "osaka-ward-flower:23hirano.jpg",
    "presentation": "cutout"
  },
  "ward-27122": {
    "src": "/region-flags/ward-27122.png",
    "alt": "Nishinari",
    "source": "osaka-ward-flower:24nishinari.jpg",
    "identity": "osaka-ward-flower:24nishinari.jpg",
    "presentation": "cutout"
  },
  "region-kansai": {
    "src": "/region-flags/region-kansai.png",
    "alt": "Kansai",
    "source": "local:region-kansai.png",
    "identity": "local:kansai-region",
    "presentation": "flag"
  },
  "region-kanto": {
    "src": "/region-flags/region-kanto.png",
    "alt": "Kantō",
    "source": "local:region-kanto.png",
    "identity": "local:kanto-region",
    "presentation": "flag"
  },
  "dcc": {
    "src": "/region-flags/dcc.png",
    "alt": "Dublin City Council",
    "source": "local:dcc.png",
    "identity": "local:dublin-city-council",
    "presentation": "flag"
  },
  "fingal": {
    "src": "/region-flags/fingal.png",
    "alt": "Fingal County Council",
    "source": "local:fingal.png",
    "identity": "local:fingal-county-council",
    "presentation": "flag"
  },
  "sdcc": {
    "src": "/region-flags/sdcc.png",
    "alt": "South Dublin County Council",
    "source": "local:sdcc.png",
    "identity": "local:south-dublin-county-council",
    "presentation": "flag"
  },
  "dlr": {
    "src": "/region-flags/dlr.png",
    "alt": "Dún Laoghaire–Rathdown",
    "source": "local:dlr.png",
    "identity": "local:dun-laoghaire-rathdown",
    "presentation": "flag"
  },
  "metro-prince-rupert": {
    "src": "/region-flags/metro-prince-rupert.png",
    "alt": "Prince Rupert",
    "source": "local:metro-prince-rupert.png",
    "identity": "local:prince-rupert",
    "presentation": "flag"
  },
  "metro-portland-maine": {
    "src": "/region-flags/metro-portland-maine.png",
    "alt": "Portland",
    "source": "local:metro-portland-maine.png",
    "identity": "local:portland-maine",
    "presentation": "flag"
  },
  "prefecture-osaka": {
    "src": "/region-flags/prefecture-osaka.png",
    "alt": "Osaka Prefecture",
    "source": "local:prefecture-osaka.png",
    "identity": "local:osaka-prefecture",
    "presentation": "flag"
  },
  "staten-island": {
    "src": "/region-flags/staten-island.png",
    "alt": "Staten Island",
    "source": "local:staten-island.png",
    "identity": "local:staten-island",
    "presentation": "flag"
  },
  "redbridge": {
    "src": "/region-flags/redbridge.png",
    "alt": "Redbridge",
    "source": "local:redbridge.png",
    "identity": "local:redbridge",
    "presentation": "cutout"
  }
} as const;

export type BundledPresetFlagSegmentId = keyof typeof BUNDLED_PRESET_FLAG_ASSETS;
